### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by guidoffm** [nuproj/nuproj#268] opened 2016-09-21 13:32 UTC
Would it be possible to add a feature to to a NuGet push after build?  We use a windows file share as NuGet server. If you set the file share as OutputPath, then only the most recent package version will survive at destination and former versions are deleted.

**Comment by AArnott** [comment] 2016-10-10 03:09
Dupe of #46

**Closed by AArnott** 2016-10-10 03:09 UTC
