### ISSUE TITLE
Deploy?

### ISSUE THREAD

**Issue by Michael-DST** [nuproj/nuproj#73] opened 2015-01-25 15:30 UTC
It would be awesome to configure a NuProj project to deploy to NuGet.org (or configured repository) when it is marked as "Deploy" in the Configuration Manager.  Of course, it would be nice to have "Deploy" available in the Configuration Manager to begin with. :)

**Comment by terrajobst** [comment] 2015-04-09 21:03
Thanks for the suggestion! This sounds like a duplicate of #46.

**Closed by terrajobst** 2015-04-09 21:03 UTC
Labels: enhancement, vs

**Comment by Michael-DST** [comment] 2015-04-09 21:06
Actually, it is a little different.  This would enable continuous deployment (or automated NuGet deployment) from a CI/CD build and would not require any UI or user interaction.  Please do consider it as a different request than #73. :)  Thank you.
