### ISSUE TITLE
Feature Request: Use Version Number for referenced assembly

### ISSUE THREAD

**Issue by ravensorb** [nuproj/nuproj#178] opened 2015-12-06 22:16 UTC
It would be great if there was an easy way to use the version information that was part of the referenced assembly (as well as other properties like Author)

**Comment by AArnott** [comment] 2015-12-09 05:46
Dupe of #20

**Closed by AArnott** 2015-12-09 05:46 UTC

**Comment by ravensorb** [comment] 2016-01-03 15:48
Great -- so how can I use this?  Can I pull in a git commit id or an assembly version?  do I need to use a specific token in my properties?

**Comment by AArnott** [comment] 2016-01-03 16:59
Personally I use Nerdbank.gitversioning to build both my assemblies and my nuproj projects. That ensures the versions are always in sync and increment reasonably.

**Comment by ravensorb** [comment] 2016-01-03 18:13
Which works well -- now we just need a way to easily prompt this to the nuspec (with its own version number if needed)

**Comment by kovalikp** [comment] 2016-01-03 18:22
You can see, how is `NerdBank.GitVersioning` is plugged into NuProj itself here https://github.com/nuproj/nuproj/blob/master/src/NuProj.Packages/NuProj.nuproj#L15 and here https://github.com/nuproj/nuproj/blob/master/src/NuProj.Packages/NuProj.nuproj#L95

**Comment by ravensorb** [comment] 2016-01-03 18:49
not working too well

1>------ Build started: Project: XLabs.Core, Configuration: Debug Any CPU ------
1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targ
1>ets(30,5): error MSB4018: The "GetBuildVersion" task failed unexpectedly.\r
1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targ
1>ets(30,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.\r
1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targ
1>ets(30,5): error MSB4018:    at Nerdbank.GitVersioning.GitExtensions.GetVersionHeight(Repository repo, String repoRelat
1>iveProjectDirectory)\r
1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targ
1>ets(30,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.Execute()\r
1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targ
1>ets(30,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Ex
1>ecute()\r
1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targ
1>ets(30,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by AArnott** [comment] 2016-01-03 21:02
@ravensorb: I see errors like this when the build executes on an already-loaded msbuild.exe process. Try building again but with the `/nr:false` switch to force all new processes to load.

**Comment by AArnott** [comment] 2016-01-03 21:04
> now we just need a way to easily prompt this to the nuspec (with its own version number if needed)

yes, I've been thinking that nuproj and nerdbank.gitversioning working 'by default' together would be worthwhile. Certainly to me. Since the VS NuGet client doesn't support NuProj, installing the NB.GV package is manual and tedious. I'd like to improve that.
Supporting project.json in nuproj itself would nearly totally solve that problem. And @kovalikp is already close to that, I think.

**Comment by kovalikp** [comment] 2016-01-03 22:23
NB.GV / NuProj could be *easily* solved, if the NuGet would provide decent CPS integration :wink: . Any news from that front?

**Comment by kovalikp** [comment] 2016-01-03 23:12
I'm not sure how project.json would help us in this case. "version" property is expected to be a static string, isn't it?

**Comment by AArnott** [comment] 2016-01-04 05:23
> I'm not sure how project.json would help us in this case. 

project.json support within the NuProj itself would allow us to manually create the project.json file (which is trivial) and add the dependency on Nerdbank.GitVersioning right there. The build would take it from there adding all the necessary imports. So lack of NuGet Client support for NuProj doesn't get in the way any more.

> "version" property is expected to be a static string, isn't it?

I'm not sure which `version` you're referring to. The one in the project.json file, yes. But I'm not proposing we use the project.json's version field. Rather, we eliminate the definition of the `<Version>` msbuild property in the .nuproj altogether because nerdbank.gitversioning sets it during the build.

**Comment by ravensorb** [comment] 2016-01-05 23:22
@AArnott I did a full reboot and am still getting the exact same errors with Nerdbank. I'll post a bug issue over there.

**Comment by AArnott** [comment] 2016-01-06 06:34
Thanks, @ravensorb. I see that, and see that I misread your report up above. Thanks for filing the issue.
